### ISSUE TITLE
Augmenting a core class is a bad idea

### ISSUE THREAD

**Issue by lizmat** [thundergnat/String-Rotate#1]
Because you cannot (at least currently) load two modules that have both augments in them at the same time.

Take this example:

    # lib/A.rakumod
    use MONKEY;
    augment class Str {
        method foo() { "foo" }
    }

    # lib/B.rakumod
    use MONKEY;
    augment class Str {
        method bar() { "bar" }
    }

and then:

    $ raku -e 'use lib "lib"; use A; use B'
    ===SORRY!=== Error while compiling -e
    STable conflict detected during deserialization.
    (Probable attempt to load a mutated module or modules that cannot be loaded together).

Perhaps it's better to export the role, and allow people to mix that role in.

    my $a = "foo" but String::Rotate;

or export a sub that you can use on any string:

    $a.&rotate(1)

Hope this made sense!

**Comment by thundergnat** [comment]
Good point. Released new version that doesn't automatically augment
